# fly.toml app configuration file generated for torrent-searcher-api-with-website on 2024-11-02T18:40:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'torrent-searcher-api-with-website'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
